M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-26T00:42:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T00:42:13+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X127.149Y-138.727
X132.929Y-138.727
M30
